#!/bin/sh
#
# Add following line to /etc/auto_master
#  /twitter        auto_twitter
#
# Add auto_twitter to /etc directory
#
# * -fstype=iumfs,user=& :twitterfs://twitter.com/
#
echo "/twitter        auto_twitter" | sudo tee -a /etc/auto_master > /dev/null
echo "* -fstype=iumfs,user=& :twitterfs://twitter.com/" | sudo tee -a /etc/auto_master > /dev/null
