#!/bin/sh

HADOOPHOME=`which hadoop | xargs dirname | xargs dirname`
CLASSPATH=\
$CONFDIR:\
$HADOOPCLASSPATH:\
$PWD/cmd/twitterfsd.jar:\
$PWD/cmd/lib/twitter4j-core-3.0.3.jar:\
$PWD/cmd/lib/twitter4j-stream-3.0.3.jar:\
$PWD/cmd/lib/iumfs-daemon-core.jar

#java -Djava.util.logging.config.file=log.prop $@ -cp $CLASSPATH com.cafeform.iumfs.twitterfs.TwitterFs
java $@ -cp $CLASSPATH com.cafeform.iumfs.twitterfs.TwitterFs
