/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package iumfs.twitterfs;

import iumfs.NotSupportedException;
import java.io.UnsupportedEncodingException;
import java.nio.ByteBuffer;

/**
 *
 * @author ka78231
 */
class SetupFile extends TwitterfsFile {
    private String script;

    SetupFile(Account account, String name){
        super(account, name);
        setScript("#!/bin/sh\n# Do not edit this file.\n" 
                + "java -cp " +  System.getProperty("java.class.path")
                + " \"$@\" " // java options, if any
                + " iumfs.twitterfs.Main setup " + account.getUsername() + "\n"
                + "if [ $? != 0 ]; then" 
                + "     echo \"\ntry\n    $ setup -Dhttp.proxyHost=<proxy_address> -Dhttp.proxyPort=<proxy_port>\" \n"
                + "fi \n"
                );
    }

    @Override
    public long getPermission() {
        return (long) 0100555; // executable
    }

    @Override
    public long read(ByteBuffer buf, long size, long offset) throws UnsupportedEncodingException {
        byte[] bytes = getScript().getBytes("UTF-8");
        /*
         * バッファに書き込む
         */
        buf.put(bytes, 0, bytes.length);        
        return bytes.length;
    }

    @Override
    public long write(byte[] buf, long size, long offset) {
        throw new NotSupportedException();
    }

    /**
     * @return the script
     */
    public String getScript() {
        return script;
    }

    /**
     * @param script the script to set
     */
    public void setScript(String script) {
        this.script = script;
        try {
            byte[] bytes = script.getBytes("UTF-8");        
            setFileSize(bytes.length);            
        } catch (UnsupportedEncodingException ex) {
            logger.severe(ex.getMessage());
        }        
    }

}
